// lib/skills.ts
//
// Canonical client-side mirror of the public.skills table (140 rows).
// Generated by querying the DB; keep in sync when the catalog migration
// adds or removes skills. The wizard renders ALL_SKILLS as the pickable
// set on the Skills step.

export type SkillCategory =
  | 'AI/ML'
  | 'Architecture'
  | 'Backend'
  | 'Big Data'
  | 'Cloud'
  | 'Coding'
  | 'Cybersecurity'
  | 'Data & Databases'
  | 'Data Science'
  | 'Database'
  | 'DevOps'
  | 'Digital Literacy'
  | 'Frontend'
  | 'Machine Learning'
  | 'Mobile'
  | 'Networking'
  | 'Programming'
  | 'Security'
  | 'Systems'
  | 'Testing';

export const ALL_SKILLS = [
  // AI/ML
  'AI', 'Computer Vision', 'LLMs', 'Machine Learning', 'Neural Network', 'NLP',

  // Architecture
  'API Design', 'Application Architecture', 'Architecture Principles', 'Caching Strategies',
  'Compliance Standards', 'Domain-Driven Design', 'IT Metrics', 'Process Automation',
  'Service Design', 'Technical Leadership', 'Workflow Automation',

  // Backend
  '.NET', 'C#', 'Django', 'Express', 'Flask', 'Go', 'GraphQL', 'Java',
  'Node.js', 'PHP', 'Python', 'REST APIs', 'Rust', 'Spring Boot',

  // Big Data
  'Hadoop', 'Spark',

  // Cloud
  'AWS', 'Azure', 'Block Storage', 'Cloud Cost Management', 'Cloud Services',
  'Cloud-native Development', 'GCP', 'Network Security', 'Object Storage',
  'Platform as a Service (PaaS)', 'Private Cloud', 'Serverless Architecture',
  'Virtual Private Cloud', 'Virtualization',

  // Coding
  'Algorithms', 'Continuous Deployment', 'Continuous Integration', 'Data Structures',
  'Databases', 'Debugging', 'Front-end / Back-end', 'Programming Languages',
  'Scripting', 'Software Design', 'Unit Testing',

  // Cybersecurity
  'Application Security', 'Cloud Security', 'Endpoint Security', 'Ethical Hacking',
  'Network Protocols', 'Penetration Testing', 'Risk Assessments', 'Security Architecture',
  'Security Auditing', 'Threat Modeling', 'Vulnerability Assessments', 'Web Security',

  // Data & Databases
  'Data Lakes', 'Data Lifecycle Management', 'Data Modeling', 'Data Profiling',
  'Database Constraints', 'Database Sharding', 'Indexing', 'Master Data Management',
  'OLTP & OLAP', 'Schema Design', 'Transactions',

  // Data Science
  'NumPy', 'Pandas', 'R',

  // Database
  'Firebase', 'MongoDB', 'MySQL', 'PostgreSQL', 'Redis', 'SQL',

  // DevOps
  'Automated Deployment', 'Automated Testing', 'Backup & Restore', 'Build Automation',
  'CI/CD', 'Containerization', 'Docker', 'Git', 'Incident Management',
  'Infrastructure as Code', 'Infrastructure Automation', 'Infrastructure Monitoring',
  'Infrastructure Provisioning', 'Kubernetes', 'Service Level Agreements',

  // Digital Literacy
  'Collaboration Tools', 'Data Analysis', 'Data Entry', 'Document Tools',
  'Email Communication', 'File Management', 'Graphic Design Tools', 'Media Tools',
  'Password Management', 'Presentation Software', 'Using Generative AI',

  // Frontend
  'Angular', 'HTML/CSS', 'JavaScript', 'Next.js', 'React', 'Sass',
  'Tailwind', 'TypeScript', 'Vue', 'Webpack',

  // Machine Learning
  'PyTorch', 'Scikit-learn', 'TensorFlow',

  // Mobile
  'Flutter', 'Kotlin', 'React Native', 'Swift',

  // Networking
  'Networking',

  // Programming
  'C', 'C++',

  // Security
  'Cryptography', 'Security',

  // Systems
  'Linux',

  // Testing
  'Testing',
] as const;

export type Skill = (typeof ALL_SKILLS)[number];

export const ALL_SKILLS_ARRAY: string[] = [...ALL_SKILLS];

export const SKILL_CATEGORIES: Record<string, SkillCategory> = {
  // AI/ML
  'AI': 'AI/ML', 'Computer Vision': 'AI/ML', 'LLMs': 'AI/ML',
  'Machine Learning': 'AI/ML', 'Neural Network': 'AI/ML', 'NLP': 'AI/ML',

  // Architecture
  'API Design': 'Architecture', 'Application Architecture': 'Architecture',
  'Architecture Principles': 'Architecture', 'Caching Strategies': 'Architecture',
  'Compliance Standards': 'Architecture', 'Domain-Driven Design': 'Architecture',
  'IT Metrics': 'Architecture', 'Process Automation': 'Architecture',
  'Service Design': 'Architecture', 'Technical Leadership': 'Architecture',
  'Workflow Automation': 'Architecture',

  // Backend
  '.NET': 'Backend', 'C#': 'Backend', 'Django': 'Backend', 'Express': 'Backend',
  'Flask': 'Backend', 'Go': 'Backend', 'GraphQL': 'Backend', 'Java': 'Backend',
  'Node.js': 'Backend', 'PHP': 'Backend', 'Python': 'Backend', 'REST APIs': 'Backend',
  'Rust': 'Backend', 'Spring Boot': 'Backend',

  // Big Data
  'Hadoop': 'Big Data', 'Spark': 'Big Data',

  // Cloud
  'AWS': 'Cloud', 'Azure': 'Cloud', 'Block Storage': 'Cloud',
  'Cloud Cost Management': 'Cloud', 'Cloud Services': 'Cloud',
  'Cloud-native Development': 'Cloud', 'GCP': 'Cloud', 'Network Security': 'Cloud',
  'Object Storage': 'Cloud', 'Platform as a Service (PaaS)': 'Cloud',
  'Private Cloud': 'Cloud', 'Serverless Architecture': 'Cloud',
  'Virtual Private Cloud': 'Cloud', 'Virtualization': 'Cloud',

  // Coding
  'Algorithms': 'Coding', 'Continuous Deployment': 'Coding', 'Continuous Integration': 'Coding',
  'Data Structures': 'Coding', 'Databases': 'Coding', 'Debugging': 'Coding',
  'Front-end / Back-end': 'Coding', 'Programming Languages': 'Coding',
  'Scripting': 'Coding', 'Software Design': 'Coding', 'Unit Testing': 'Coding',

  // Cybersecurity
  'Application Security': 'Cybersecurity', 'Cloud Security': 'Cybersecurity',
  'Endpoint Security': 'Cybersecurity', 'Ethical Hacking': 'Cybersecurity',
  'Network Protocols': 'Cybersecurity', 'Penetration Testing': 'Cybersecurity',
  'Risk Assessments': 'Cybersecurity', 'Security Architecture': 'Cybersecurity',
  'Security Auditing': 'Cybersecurity', 'Threat Modeling': 'Cybersecurity',
  'Vulnerability Assessments': 'Cybersecurity', 'Web Security': 'Cybersecurity',

  // Data & Databases
  'Data Lakes': 'Data & Databases', 'Data Lifecycle Management': 'Data & Databases',
  'Data Modeling': 'Data & Databases', 'Data Profiling': 'Data & Databases',
  'Database Constraints': 'Data & Databases', 'Database Sharding': 'Data & Databases',
  'Indexing': 'Data & Databases', 'Master Data Management': 'Data & Databases',
  'OLTP & OLAP': 'Data & Databases', 'Schema Design': 'Data & Databases',
  'Transactions': 'Data & Databases',

  // Data Science
  'NumPy': 'Data Science', 'Pandas': 'Data Science', 'R': 'Data Science',

  // Database
  'Firebase': 'Database', 'MongoDB': 'Database', 'MySQL': 'Database',
  'PostgreSQL': 'Database', 'Redis': 'Database', 'SQL': 'Database',

  // DevOps
  'Automated Deployment': 'DevOps', 'Automated Testing': 'DevOps',
  'Backup & Restore': 'DevOps', 'Build Automation': 'DevOps', 'CI/CD': 'DevOps',
  'Containerization': 'DevOps', 'Docker': 'DevOps', 'Git': 'DevOps',
  'Incident Management': 'DevOps', 'Infrastructure as Code': 'DevOps',
  'Infrastructure Automation': 'DevOps', 'Infrastructure Monitoring': 'DevOps',
  'Infrastructure Provisioning': 'DevOps', 'Kubernetes': 'DevOps',
  'Service Level Agreements': 'DevOps',

  // Digital Literacy
  'Collaboration Tools': 'Digital Literacy', 'Data Analysis': 'Digital Literacy',
  'Data Entry': 'Digital Literacy', 'Document Tools': 'Digital Literacy',
  'Email Communication': 'Digital Literacy', 'File Management': 'Digital Literacy',
  'Graphic Design Tools': 'Digital Literacy', 'Media Tools': 'Digital Literacy',
  'Password Management': 'Digital Literacy', 'Presentation Software': 'Digital Literacy',
  'Using Generative AI': 'Digital Literacy',

  // Frontend
  'Angular': 'Frontend', 'HTML/CSS': 'Frontend', 'JavaScript': 'Frontend',
  'Next.js': 'Frontend', 'React': 'Frontend', 'Sass': 'Frontend',
  'Tailwind': 'Frontend', 'TypeScript': 'Frontend', 'Vue': 'Frontend', 'Webpack': 'Frontend',

  // Machine Learning
  'PyTorch': 'Machine Learning', 'Scikit-learn': 'Machine Learning', 'TensorFlow': 'Machine Learning',

  // Mobile
  'Flutter': 'Mobile', 'Kotlin': 'Mobile', 'React Native': 'Mobile', 'Swift': 'Mobile',

  // Networking
  'Networking': 'Networking',

  // Programming
  'C': 'Programming', 'C++': 'Programming',

  // Security
  'Cryptography': 'Security', 'Security': 'Security',

  // Systems
  'Linux': 'Systems',

  // Testing
  'Testing': 'Testing',
};

export const getSkillCategory = (skill: string): SkillCategory =>
  SKILL_CATEGORIES[skill] ?? 'Coding';

export const SKILL_TO_INDEX = new Map<string, number>(
  ALL_SKILLS.map((skill, i) => [skill, i])
);

const ALL_SKILLS_SET = new Set<string>(ALL_SKILLS);

export const isValidSkill = (name: string): name is Skill =>
  ALL_SKILLS_SET.has(name);

export const validateSkills = (skills: string[]): Skill[] =>
  skills.filter(isValidSkill);

export const skillsToVector = (skills: string[]): number[] => {
  const vector = new Array(ALL_SKILLS.length).fill(0);
  for (const skill of skills) {
    const idx = SKILL_TO_INDEX.get(skill);
    if (idx !== undefined) vector[idx] = 1;
  }
  return vector;
};
